### ISSUE TITLE
NLST dataset problem

### ISSUE THREAD

**Issue by computerAItest** [cwmok/DIRAC#10]
Could you please provide the train file of the model trained on the MICCAI 2022 task1 task, I see only the training and test files of the OASIS dataset, if you can provide it, I would be very grateful

**Comment by cwmok** [comment]
Hi @yuanpengpeng,

This repository is about brain tumor registration, not the lung inhale-exhale registration. If you want to download the NLST dataset, you may go to the learn2reg challenge at https://learn2reg.grand-challenge.org/Datasets/. You will need to register for the challenge first.

**Comment by computerAItest** [comment]
> Hi @yuanpengpeng,
> 
> This repository is about brain tumor registration, not the lung inhale-exhale registration. If you want to download the NLST dataset, you may go to the learn2reg challenge at https://learn2reg.grand-challenge.org/Datasets/. You will need to register for the challenge first.
![1681201616656](https://user-images.githubusercontent.com/60032308/231101721-5afcde6a-44b9-4457-9a6f-bfcf13f5c4a3.png)

Hello, I see that you have submitted in the leaderboards of the MICCAI 2022 challenge task1 lung registration task, and the ranking is relatively high. Is this model not in this repository?
Can you share the code of this model, I will be very grateful

**Comment by cwmok** [comment]
The one you saw in the leaderboard is not in this repository. I submitted a paper to MICCAI2023 this year. If accepted, I will release the code in another repository.
