### ISSUE TITLE
Tumor mask

### ISSUE THREAD

**Issue by chongweiwu** [cwmok/DIRAC#12]
dear author, thanks for your excellent work. I have several questions about the tumor masks :
first, wether the tumor used in the measurement contains the edema areas? second, have you done  any post-treatment on the segmented tumor masks? third,  what is the dilation structure, in your work, during the morphological dilation of tumors?

**Comment by cwmok** [comment]
Dear @chongweiwu,

1. During the evaluation, the tumor mask we used only contained the tumor core (whole tumor without the edema).
2. No, we don't have any post-processing to the segmented tumor masks.
3. The structure we used is an element with square connectivity equal to one. (scipy.ndimage.binary_dilation)

**Comment by chongweiwu** [comment]
I am really appreciate for your detailed reply. I’m worried that my divided two landmarks sets may differ from yours, so can you provide me with the source code, dilated tumor images or the divided two landmarks sets?
my email adress is chongweiwu@hust.edu.cn
thanks

**Comment by cwmok** [comment]
Suppose `tumor_seg` is a segmentation map of the tumor core, we first do the binary dilation as follows:

`from scipy.ndimage import binary_dilation`
`tumor_seg = binary_dilation(tumor_seg, iterations=30)`

Then, to determine the class (tumor/non-tumor region) of each landmark, a simple if-else statement is used:
```
for i in range(Y_label.shape[0]):
    if tumor_seg[int(Y_label[i][0]), int(Y_label[i][1]), int(Y_label[i][2])] == 1:
        print("Tumor", Y_label[i])
        Y_label_tumor.append(Y_label[i])
        X_label_tumor.append(X_label[i])
    else:
        print("Non-Tumor", Y_label[i])
        Y_label_nontumor.append(Y_label[i])
        X_label_nontumor.append(X_label[i])
```

**Comment by chongweiwu** [comment]
Thank you again for your kindly reply!
