### ISSUE TITLE
normalized the deformation field

### ISSUE THREAD

**Issue by 18370029656** [cwmok/DIRAC#14]
Hello, why do we need to normalize the deformation field flow and control the deformation variable to [-1,1], so that the maximum deformation does not exceed 1. Is this not very reasonable?

**Comment by cwmok** [comment]
Hi @18370029656,

This is inspired by [ICNet](https://github.com/zhangjun001/ICNet). Basically, we want to restrict the maximum deformation potential of the network with the range_flow, since we focused on local non-linear deformation.

**Comment by 18370029656** [comment]
Hello, may I ask if there is anything I need to pay attention to when applying your idea to other frameworks? The regions without corresponding relationships that I calculated are always at the edges, as shown in the figure.
![)4L $R XMH2X4GVC 0V0E6K](https://github.com/cwmok/DIRAC/assets/108872700/e5283aaf-5641-4420-bf1c-eed55b3b0522)

**Comment by cwmok** [comment]
You should figure out the best combination of thresh_fw, thresh_bw and reg_code .

thresh_fw, thresh_bw: threshold of the missing correspondence regions for the forward and backward registration.  (larger threshold = less sensitive to small missing correspondence regions.)
reg_code: the weight of the smoothness regularization. (higher weight = smoother deformation field, less deformation potential.)

**Comment by 18370029656** [comment]
thanks for your quick reply！



---Original---
From: "Tony ***@***.***&gt;
Date: Wed, Nov 22, 2023 16:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cwmok/DIRAC] normalized the deformation field (Issue #14)




 
You should figure out the best combination of thresh_fw, thresh_bw and reg_code .
 
thresh_fw, thresh_bw: threshold of the missing correspondence regions for the forward and backward registration.  (larger threshold = less sensitive to small missing correspondence regions.)
 reg_code: the weight of the smoothness regularization. (higher weight = smoother deformation field, less deformation potential.)
