### ISSUE TITLE
issue about the calculation of metric

### ISSUE THREAD

**Issue by 18370029656** [cwmok/DIRAC#15]
Hello, I'm sorry to bother you. I have some questions about the calculation of the evaluation metrics mentioned in your paper, and I hope to receive your answer. 
When calculating the metrics, you divided them into two sets: near the tumor area and far from the tumor area. Does the near tumor area include the tumor area? If the tumor area is not included, why are the metrics values near the tumor area generally much lower than those far away from the tumor area when you have already ruled out the influence of the tumor area

**Comment by cwmok** [comment]
Hi @18370029656, the whole tumor is included in the near tumor area as defined in the paper.

**Comment by 18370029656** [comment]
ok,thanks for your quick reply!

**Comment by 18370029656** [comment]
Hello, may I ask if the near tumor region within 30mm from the tumor region is calculated from the tumor center or from the tumor boundary when dividing the area?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cwmok/DIRAC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月8日(星期一) 晚上10:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cwmok/DIRAC] issue about the calculation of metric (Issue #15)





 
Hi @18370029656, the whole tumor is included in the near tumor area as defined in the paper.

**Comment by cwmok** [comment]
@18370029656 It is computed from tumor boundary.

**Comment by 18370029656** [comment]
Okay, thanks for your quick reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cwmok/DIRAC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月29日(星期一) 下午3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cwmok/DIRAC] issue about the calculation of metric (Issue #15)





 
@18370029656 It is computed from tumor boundary.

**Comment by 18370029656** [comment]
Hello, I have a little question for you about the calculation of evaluation indicators. When comparing VM with VM-CM, I found that in the group of near-tumour regions, the values of the metrics (dice, etc.) are higher in VM than in VM-CM, is this not reasonable? My understanding is that the VM method forces the alignment of the tumour images in the near tumour region because it does not consider the tumour region separately, whereas the VM-CM excludes the effect of the tumour region and does not take into account the similarity of the tumour region, so the metrics values will be lower. May I ask if my understanding is accurate? Looking forward to your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "123"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月29日(星期一) 下午3:56
***@***.***&gt;;

主题:&nbsp;回复： [cwmok/DIRAC] issue about the calculation of metric (Issue #15)



Okay, thanks for your quick reply!




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "cwmok/DIRAC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月29日(星期一) 下午3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cwmok/DIRAC] issue about the calculation of metric (Issue #15)





 
@18370029656 It is computed from tumor boundary.
