### ISSUE TITLE
issue about δbf 

### ISSUE THREAD

**Issue by 18370029656** [cwmok/DIRAC#16]
Hello, I'm sorry to bother you. I would like to ask you how to view the δbf effect plot in your paper？ Can you share the code to save or view the δbf?
<img width="302" alt="image" src="https://github.com/cwmok/DIRAC/assets/108872700/1cd66e25-669e-4889-8bea-8145f22ea273">

**Comment by cwmok** [comment]
Hi @18370029656,

I use seaborn to plot this figure. 
`
import seaborn as sns

ax = sns.heatmap(df, annot=True, fmt=".2f", cbar_kws={'ticks': np.linspace(min_t, max_t, 3)}, vmin=min_t, vmax=max_t)
`

**Comment by cwmok** [comment]
Hi @18370029656,

I use seaborn to plot this figure.

`
import seaborn as sns

  ax=sns.heatmap(diff_map[:, :, t_x].T, xticklabels=False, yticklabels=False)

`
