### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by Who-Tu** [cwmok/DIRAC#5]
Hello, could you please share the data set used? I can't get it from their website.

**Comment by cwmok** [comment]
Hi @Who-Tu, 

I do not have the right to re-distribute the data under the data license. But you can create an account at [ipp.cbica.upenn.edu](https://ipp.cbica.upenn.edu/) and follow the instruction [here](https://www.med.upenn.edu/cbica/brats-reg-challenge/#RegistrationDataRequest7) to apply for it. It should be easy to do so.

**Comment by Who-Tu** [comment]
Ok, I'll try again. Thank you.
