### ISSUE TITLE
alpha的取值问题

### ISSUE THREAD

**Issue by 18370029656** [cwmok/DIRAC#8]
<img width="567" alt="image" src="https://user-images.githubusercontent.com/108872700/230904951-4347dbc8-2d34-40e1-b8b0-b1a278655a0b.png">
请问在这一步中，alpha=0.015具体是怎么得到的？对于一个新的数据集，应该怎么计算对应的alpha值？期待您的回答

**Comment by cwmok** [comment]
> Hi @18370029656,
> 
> We selected the alpha value based on the forward and backward error maps of the validation set, and we found it generalized well to the test set. An ideal alpha value should be able to highlight regions with absent correspondence, e.g., tumor and resected tumor region, while excluding the regions with valid correspondence. A more rigorous way to choose the alpha is to measure the overlap (e.g. Dice score) of thresholded region and the tumor region of the validation set.
