### ISSUE TITLE
why alpha

### ISSUE THREAD

**Issue by 18370029656** [cwmok/DIRAC#9]
<img width="567" alt="image" src="https://user-images.githubusercontent.com/108872700/230905704-c8e78299-1ed5-491f-9379-a4eb8223fec2.png">

In this step, how exactly does alpha=0.015 get it? For a new data set, how should the corresponding alpha value be calculated? Looking forward to your answer

**Comment by cwmok** [comment]
Hi @18370029656,

We selected the alpha value based on the forward and backward error maps of the validation set, and we found it generalized well to the test set. An ideal alpha value should be able to highlight regions with absent correspondence, e.g., tumor and resected tumor region, while excluding the regions with valid correspondence.  A more rigorous way to choose the alpha is to measure the overlap (e.g. Dice score) of thresholded region and the tumor region of the validation set.
